### ISSUE TITLE
Incorrect Tooth codes.

### ISSUE THREAD

**Issue by zgypa** [open-ortho/dicom4ortho#4]
After reviewing the tooth codes briefly with Mark Jurkovich, we have found that some of them are incorrect. They will have to be corrected in WP1100 first, then implemented here again here.

**Comment by zgypa** [comment]
According to @moonholly  on 2020-12-12, All deciduous and permanent tooth codes have been corrected to the most granular codes. Therefore we are ready to implement these.

**Comment by zgypa** [comment]
The issue lies in the fact that the tooth codes are defined in CID-4018 and CID-4019 of DICOM. And i think we need to use those. And there are a couple of them which are incorrect there. I emailed David Clunie to ask for help on how to move next.

**Comment by acasertano** [comment]
Which codes are incorrect?   This can be added to our existing CPs.
